### ISSUE TITLE
Example project fails to build

### ISSUE THREAD

**Issue by aaronbrethorst** [applidium/ADOverlayContainer#1]
I'm seeing two errors in the example project when I try building it.
Repro:

1. Download project via https
2. Navigate to example project directory in terminal
3. `pod install`
4. Open xcworkspace
5. Cmd+R

Expected: Project builds and runs.

Actual: Two errors prevent building

```
:-1: /Users/aaron/Downloads/ADOverlayContainer-master/Example/Pods/Pods/Target Support Files/Pods-OverlayContainer_Example/Pods-OverlayContainer_Example.debug.xcconfig: unable to open file (in target "OverlayContainer_Example" in project "OverlayContainer") (in target 'OverlayContainer_Example')

:-1: /Users/aaron/Downloads/ADOverlayContainer-master/Example/Pods/Pods/Target Support Files/Pods-OverlayContainer_Tests/Pods-OverlayContainer_Tests.debug.xcconfig: unable to open file (in target "OverlayContainer_Tests" in project "OverlayContainer") (in target 'OverlayContainer_Tests')
```

**Comment by gaetanzanella** [comment]
Hi @aaronbrethorst, thanks for the issue.

I downloaded master and it works. Be sure to execute 3 before 4. I use Xcode 10.1 and I tried with cocoapods 1.5.3 & 1.6.0 beta.

I will integrate Travis soon. Let me know.

**Comment by marcinmatczuk** [comment]
Doesn't work as well. Xcode 10.1, pods 1.5.3.

`pod install` output also includes this:
```
[!] The version of CocoaPods used to generate the lockfile (1.6.0.beta.1) is higher than the version of the current executable (1.5.3). Incompatibility issues may arise.
```
that could be the reason, but I think it's something on your machine, @gaetanzanella, that is not reflected in the codebase.

**Comment by gaetanzanella** [comment]
Right, I used cocoapods 1.6.0 beta because of https://github.com/CocoaPods/CocoaPods/issues/7708

I downgraded to 1.5.3. It should be good now. Thank you !

**Comment by gaetanzanella** [comment]
Right, I used cocoapods 1.6 beta because of https://github.com/CocoaPods/CocoaPods/issues/7708.

I regenerated the project using cocoapods 1.5.3. It should be good now. Thanks !
