### ISSUE TITLE
Not working properly when added source folder directly without installling pods

### ISSUE THREAD

**Issue by kunusiths** [applidium/ADOverlayContainer#10]
Hello sir,
child.didMove(toParentViewController: self) and child.didMove(toParent: self) are these both the same?. i am getting error and in child.didMove(toParent: self) so i renamed it to child.didMove(toParentViewController: self) .but i am getting other issue when i added this in my app.
i am not able to drag back ground map view but scroll view is scrolling.

when i installed using pods,drag is working fine.
but when i directly add source folder,its not working.please help.

**Comment by gaetanzanella** [comment]
OverlayContainer is written in Swift 4.2. Your projects is not using it. Please consider updating or use https://github.com/applidium/ADOverlayContainer/tree/swift4.1

**Comment by kunusiths** [comment]
can you please list main differences between these versions please.

**Comment by kunusiths** [comment]
?can u help me locate why the map is not able to drag please.

________________________________
