### ISSUE TITLE
Trigger Translation to certain Notch from code?

### ISSUE THREAD

**Issue by joustava** [applidium/ADOverlayContainer#13]
Hi, thanks for creating this library.

I have a usecase where I would like to display the Overlay at a later point and not immediately in a StackedViewController as in the examples. Few options that might help me in this are:
1. Trigger the translations to each Notch position from code?
2. `present` the OverlayContainerView from code?
3. Use an own UIViewControllerTransitioningDelegate?

Do any of them make sense if so are there some examples (might have overlooked something and I'm rather new to iOS and Swift).

**Comment by joustava** [comment]
Oops and sorry your example code for multiple overlays is what I was looking for! ❤️

**Comment by gaetanzanella** [comment]
hi @joustava, this is a good question. 

You're right. A good way to do it would be to add an extra empty view controller as the root view controller of a container view controller (the `OverlayNavigationViewController` for example) added to your `OverlayContainerViewController` instance :
```
class EmptyViewController: UIViewController {
    override func loadView() {
        view = PassThroughView() // required to dispatch the touches
    }
}
```
You could also try to play with the `invalidateNotchHeights` method : moving from a overlay with one 0 height notch to the actual number of notches you wish to display.

**Comment by joustava** [comment]
Thanks for your reply @gaetanzanella 

Your root view suggestion works great. I don't seem to be needing a `PassThroughView` in my case as I don't need to propagate any events to the 'main' (in your examples a map) view. 

## 👍
