### ISSUE TITLE
Dismissable by swipe

### ISSUE THREAD

**Issue by joustava** [applidium/ADOverlayContainer#14]
Is it possible to dismiss the overlay by swiping down with a certain velocity?

I was thinking that it might be possible to hook into the process before/while the notch policy would kick-in or even do this with a notch policy, but somehow that seems kludgy and I am not sure this is the way to go. Any pointers are welcome.

**Comment by gaetanzanella** [comment]
Because you already asked a question on a way to dismiss the overlay, I suppose you have a container view controller wrapping your actual overlay. 

Did you try to implement the delegate of your scrollView and to dismiss the overlay when the user's finger reaches a certain velocity ?

**Comment by kunusiths** [comment]
?fuck you

________________________________
