### ISSUE TITLE
Carthage build not compatible with XCode 10.2 / Swift 5

### ISSUE THREAD

**Issue by cofa-gaby** [applidium/ADOverlayContainer#15]
With XCode 10.2 and Swift 5, building `ADOverlayContainer` fails because the Nimble dependency is not compatible with the new Swift toolchain. 

Currently `ADOverlayContainer` is referencing:
```
github "Quick/Nimble" ~> 7.3
github "Quick/Quick" ~> 1.3
```
But these Nimble versions still use the Swift 3 toolchain which is no longer supported in the XCode 10.2 build tools. 

This can be solved by updating the Nimble dependencies to the latest versions:
```
github "Quick/Nimble" ~> 8.0
github "Quick/Quick" ~> 2.0
```

It would be great, if you could update that. (I know, I could have made a pull request for that but I found that overkill — and also I don't know about your test setup and if you can simple upgrade Nimble or if there are breaking changes in version 8)

Thanks for your great work on this framework! 💜

**Comment by gaetanzanella** [comment]
Thanks for the detailed issue !

OverlayContainer 1.1.2 is out. Could you try it ?

**Comment by cofa-gaby** [comment]
Thanks for the fast fix!
It is working now.
