### ISSUE TITLE
I want to detect when moveOverlay()'s animation done

### ISSUE THREAD

**Issue by Minsoo-kim92** [applidium/ADOverlayContainer#19]
I want to make `OverlayContainerViewController`'s dismiss animation

the animation would be like this : when NavigationVC stack's size became to 0, `OverlayContainerViewController` is going to call `moveOverlay()` with zero index of notch's height  and I want to remove the `OverlayViewController` when the `moveOverlay`'s animation is done 

But `translationController?.moveOverlay` hasn't completionHandler should I add a completionHadnler manually? or there is another way to detect when `moveOverlay()`'s animation is done ?

**Comment by gaetanzanella** [comment]
In ```    func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                        didEndDraggingOverlay overlayViewController: UIViewController,
                                        transitionCoordinator: OverlayContainerTransitionCoordinator)``` you get a transition coordinate which lets you add completion block when a transition ends.

Let me know if it's enough. Adding a completion block at `moveOverlay(toNotchAt:)` won't be too difficult.

**Comment by joustava** [comment]
@gaetanzanella I guess the use case for this is when one wants to move without dragging.
afaik it would only need changes in 
OverlayContainerViewController:
```
public func moveOverlay(toNotchAt index: Int, animated: Bool, completion: @escaping (UIViewAnimatingPosition) -> Void = {_ in}) {
        if !overlayContainerConstraintsAreActive {
            view.layoutIfNeeded()
        }
        translationController?.moveOverlay(toNotchAt: index, velocity: .zero, animated: animated, completion: completion)
    }
```

and e.g HeightContrainstOverlayTranslationController (?)
```

    func moveOverlay(toNotchAt index: Int, velocity: CGPoint, animated: Bool, completion: @escaping (UIViewAnimatingPosition) -> Void) {
        guard let overlay = overlayViewController else { return }
        assert(
            index < configuration.numberOfNotches(),
            "Invalid notch index (\(index)). The overlay can not be moved to an index greater or equal to the number of notches (\(configuration.numberOfNotches()))"
        )
        let height = translationHeight
        translationEndNotchIndex = index
        dragOverlay(toHeight: translationEndNotchHeight)
        guard animated else { return }
        let context = ConcreteOverlayContainerContextTransitioning(
            overlayViewController: overlay,
            overlayTranslationHeight: height,
            velocity: velocity,
            targetNotchIndex: translationEndNotchIndex,
            targetNotchHeight: translationEndNotchHeight,
            notchHeightByIndex: configuration.notchHeightByIndex
        )
        let animationController = configuration.animationController(forOverlay: overlay)
        let animator = animationController.interruptibleAnimator(using: context)
        let coordinator = InterruptibleAnimatorOverlayContainerTransitionCoordinator(
            animator: animator,
            context: context
        )
        delegate?.translationController(
            self,
            willReachNotchAt: translationEndNotchIndex,
            transitionCoordinator: coordinator
        )
        animator.addCompletion?(completion)
        animator.startAnimation()

    }
```

**Comment by joustava** [comment]
@gaetanzanella there is a typo in the classname `HeightContrainstOverlayTranslationController` btw.

**Comment by gaetanzanella** [comment]
Feel free to contribute @joustava

**Comment by joustava** [comment]
@gaetanzanella sure, I can have a stab at it! Is my assumption in the my previous comment correct?

**Comment by gaetanzanella** [comment]
I would make the completion optional and I don't thing `UIViewAnimatingPosition` is useful. Otherwise, it looks good to me.

**Comment by Minsoo-kim92** [comment]
Should close this issue i think, because completion was merged

**Comment by gaetanzanella** [comment]
1.3.0 is out
