### ISSUE TITLE
Wrong container Inset

### ISSUE THREAD

**Issue by alexsteinerde** [applidium/ADOverlayContainer#23]
I added a UINavigationController to the BackdropExampleViewController:
```
overlayController.viewControllers = [UINavigationController(rootViewController: searchViewController)]
```
Now there is space on top of the navigation bar when I let the swipe to the maximum state. When I drag it there it is fixed. 
![IMG_A0B96DA1203E-1](https://user-images.githubusercontent.com/5408221/55563016-68fe8e00-56f5-11e9-98b5-e57cdada7dc6.jpeg)

I already tried setting `automaticallyAdjustsScrollViewInsets = false` on the navigation controller.
Could someone please help me fixing this?

**Comment by gaetanzanella** [comment]
Hi @alexsteinerde,

I tried to add a `UINavigationController ` in the backdrop example and the layout was fine. I guess you added constraints relative to the top safe area.

Could you be more specific ? Which device did you use ? What change did you make ?
