### ISSUE TITLE
addChild not recognized

### ISSUE THREAD

**Issue by diegogarciar** [applidium/ADOverlayContainer#24]
Hi, 
I just upgraded from 1.1.2 to 1.3.0 and the extension
`func addChild(_ child: UIViewController, in containerView: UIView) `
was not recognized by my app, suggesting me to use UIKit's addChild(). I checked the code differences and the only difference I could find was the that in 1.1.2 the methods are marked as public. Even tough XCode says public is redundant.
I cleaned the app and still had to revert to 1.1.2

I like your library! nice work!

**Comment by Minsoo-kim92** [comment]
Because the extension function's scope was changed to private in this [commit](https://github.com/applidium/ADOverlayContainer/commit/c8d65bcb0216af1a117b4cce6af5218b84e9c263)

**Comment by gaetanzanella** [comment]
Hi @Minsoo-kim92, `OverlayContainer` 2.0.0 is out. `addChild(_:,in:)` is not necessary any more.
