### ISSUE TITLE
Latest stable Cocoapods version 1.6.1 fails to parse swift_versions option

### ISSUE THREAD

**Issue by eligat** [applidium/ADOverlayContainer#27]
If a Podfile specifies ADOverlayContainer dependency by commit like so:
`pod 'OverlayContainer', :git => 'https://github.com/applidium/ADOverlayContainer.git', :commit => '570dc63ca719db8f98bf46ea726d228a3204ed3d'`

Then command `pod install` fails:
```
[!] Failed to load 'OverlayContainer' podspec:
[!] Invalid `OverlayContainer.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="OverlayContainer">
Did you mean?  swift_version=
               swift_version.

 #  from /var/folders/8g/86qwfhy13c9cgkyw0pw04k5c0000gn/T/d20190502-74201-1hkatng/OverlayContainer.podspec:15
 #  -------------------------------------------
 #    s.swift_version    = '4.2'
 >    s.swift_versions = ['4.2']
 #
 #  -------------------------------------------
```

And this issue on CocoaPods github page tells that `swift_versions` option will only be available when 1.7.0 is released: https://github.com/CocoaPods/CocoaPods/issues/8191

That is a problem for people who would like to make a fork and specify an exact commit
Is this option even necessary now? 

P.S: Thanks for this beautiful framework!

**Comment by gaetanzanella** [comment]
Hi @eligat, 

I definitely should use the last stable cocoapods version. Thanks for pointing me that. 2.0.1 is out !
