### ISSUE TITLE
Stopping at top

### ISSUE THREAD

**Issue by zimmermannubique** [applidium/ADOverlayContainer#31]
In the MapsLikeViewController-Example with an iPhone 6S and changing the notch heights to
```
    private func notchHeight(for notch: OverlayNotch, availableSpace: CGFloat) -> CGFloat {
        switch notch {
        case .maximum:
            return availableSpace * 9 / 10
        case .minimum:
            return availableSpace * 1 / 4
        }
    }
```
the scrolling of the tableview is not followed through, it stops at the top notch and the tableview does not begin to scroll. First rounding the notch values (or cast to Int and back to CGFloat) solves the problem.

[Untitled.mov.zip](https://github.com/applidium/ADOverlayContainer/files/3347103/Untitled.mov.zip)

**Comment by gaetanzanella** [comment]
Thanks for the issue @zimmermannubique ! There was a serious issue on how values were rounded. It should be fixed in 3.0.1.
