### ISSUE TITLE
Corner radius?

### ISSUE THREAD

**Issue by karlshea** [applidium/ADOverlayContainer#33]
I'm having a hard time figuring out where to make the overlay controller have a corner radius. Can you point me in the right direction?

**Comment by karlshea** [comment]
Good lord of course I figured it out seconds after I posted. Never mind!

**Comment by farismhmd1** [comment]
I'm having the same issue now. can you tell me how did you do this?

**Comment by karlshea** [comment]
It looks like I fixed it in `viewDidLoad` by setting `layer.cornerRadius`.

**Comment by wrightak** [comment]
I am also having a similar issue. I do something like this: 

```
let highlightedWordDetailViewController = HighlightedWordDetailViewController()
overlayContainerViewController.viewControllers = [highlightedWordDetailViewController]
```

Inside HighlightedWordDetailViewController, in viewDidLoad, I do this:

```
        view.layer.cornerRadius = 5.0
        view.layer.shadowOpacity = 0.10
        view.layer.shadowOffset = CGSize(width: 0, height: 5)
        view.layer.shadowRadius = 5
        view.layer.shadowColor = shadowColor
```

Looking in the view debugger, I see that the bottom two corners are rounded, but the top two aren't. Can anyone give me some tips on how to solve this?
