### ISSUE TITLE
How do I use this in Swift 4.1 and XCode 9.4.1?

### ISSUE THREAD

**Issue by jayarajb1116** [applidium/ADOverlayContainer#4]

**Comment by gaetanzanella** [comment]
Hi jayarajb1116, did you try to use it ? What error message did you get ?

**Comment by jayarajb1116** [comment]
I'm using Xcode 9.4.1. I installed cocoa pods. It shows errors as the framework is not in swift 4.1.
it asked me to change the syntax to swift 4.1. I want to know whether the framework will work in Swift 4.1.

**Comment by gaetanzanella** [comment]
I created the branch [swift4.1](https://github.com/applidium/ADOverlayContainer/tree/swift4.1). Does it work in your case ?
