### ISSUE TITLE
`reloadNotchHeights()` should be exposed

### ISSUE THREAD

**Issue by fl034** [applidium/ADOverlayContainer#6]
I have a situation where my notch heights are changing, so I found the function `OverlayContainerViewControllerConfiguration.reloadNotchHeights()` which does the job.
Unfortunately the `configuration` property inside `OverlayContainerViewController` is private so I can't call it.

As a quick workaround you could declare `configuration` as `private(set)` which allows reading the variable.

**Comment by gaetanzanella** [comment]
Hi fl034, thanks for the feedback !

I was expecting this need but I couldn't figure a proper use case. Calling `reloadNotchHeights` will update the layout immediately without any animation. Would you show me your scenario ?

You can try to update the overlay container's delegate : 
```
let previousDelegate = overlayContainer.delegate
overlayContainer.delegate = nil // not needed if you handle the new layout with a new delegate object 
overlayContainer.delegate = previousDelegate
```
It should trigger a new computations pass. If you need to animate the change, try to do the same logic in an animation block : 

```
UIView.animate(withDuration: 2) {
    let previousDelegate = overlayContainer.delegate
    overlayContainer.delegate = nil
    overlayContainer.delegate = previousDelegate
    window?.layoutIfNeeded()
}
```
I will think at a better solution based on what you're trying to do 🙂

**Comment by fl034** [comment]
_I didn't mention before that I appreciate your work within this project and reading your SO answer with the detailed explanation was awesome! 👍_ 

In my case I have my overlay with a single label containing a hint for the user. Then I have a dynamic `UITableView` containing 1-n elements. Those elements change as the user scans QR-Codes.
So the notch heights are changing and this should be animated.

Your first workaround didn't work because the notch heights for the notches other than the current are differing in my case. So in Line 158 in `OverlayContainer` it won't get past the guard statement as the current sizes stay the same.

So I've forked your project and am now calling `reloadNotchHeights()` and then move the overlay to the next notch.

Another approach would be that you do a height reload before every time the user calls the method `moveOverlay(toNotchAt:, animated:)`. Could this have any downsides?

**Comment by fl034** [comment]
Thanks for your efforts. I tested your new code, but it seems to remove the animation.

Let's say I'm at notch `index = 0`. Then my context changes and I want the overlay to move up programmatically, but define the new position as `index = 0` so I can't move it down afterwards.
This is possible by calling `reloadNotchHeights` and then call `moveOverlay(toNotchAt:animated:)`.

Your new function `invalidateNotchHeights` calls `view.setsNeedsLayout()`. But you're calling `layoutIfNeeded()` here: https://github.com/applidium/ADOverlayContainer/blob/218c2f19a163c8ad0318ec3faae1100bd6449c6d/OverlayContainer/Classes/OverlayContainerViewController.swift#L132-L135

This leads to a call of `viewWillLayoutSubviews()` and `updateOverlayConstraints(forNew:)` where the following line will be called, with `animated = false` : https://github.com/applidium/ADOverlayContainer/blob/218c2f19a163c8ad0318ec3faae1100bd6449c6d/OverlayContainer/Classes/OverlayContainerViewController.swift#L169

My use case is working with calling only `reloadNotchHeights` before `moveOverlay(...)`.

**Comment by fl034** [comment]
I would prefer this over a call of `layoutIfNeeded` on the whole window to change the layout of a library controlled interface. The library should offer me a function for everything which is related to it. Calling `layoutIfNeeded` could always be triggering other layout stuff too which I don't want.

Also I know that my `notch = 0` height has changed, so the overlay has to move. So intuitively, I would invalidate the heights and calling `moveOverlay` at the same index again to do this.

Your approach works for my use case (notch height 0 changed). 
But it does crash at the following line, when I'm at `notch = 1` and after reloading the notches I end up having only one notch and call the code like you proposed.

https://github.com/applidium/ADOverlayContainer/blob/b5fc1d327001b690b334edf96d80dcebcbb4c784/OverlayContainer/Classes/Internal/HeightContraintOverlayTranslationController.swift#L97-L100

**Comment by gaetanzanella** [comment]
I agree about the window. I only use it for convenience reasons in my examples. I updated the branch. You should be able to call `moveOverlay` right after `invalidateNotchHeights` to animate the change.

About your crash, it makes sens to me. If you invalidate the notch heights while the overlay is currently at a notch which is not in the new notch ranges, the overlay is in a ambiguous state. You have to move it to a correct notch. Don't you think ?

**Comment by gaetanzanella** [comment]
I merged the change. One of my colleagues needed it. Feel free to comment the update in the future @fl034 🙂.
