### ISSUE TITLE
can width of overlay view can be reduced?

### ISSUE THREAD

**Issue by kunusiths** [applidium/ADOverlayContainer#9]
i mean width of scroll view if reduced,map view can be seen partially while scrolling.

in default case, scroll view is completely blocking map view.
![screen shot 2019-02-20 at 3 38 26 pm](https://user-images.githubusercontent.com/46209817/53083872-b3e98b00-3525-11e9-867c-34938d4ab531.png)

**Comment by gaetanzanella** [comment]
Hi kunusiths, sorry but I don't understand your question. What do you call "default case"?

If you're using the `StackViewController` provided in the examples, you can of course reduced the width of the overlay container.

**Comment by kunusiths** [comment]
Can u please tell how to keep gap in back view and slide view

**Comment by kunusiths** [comment]
> Hi kunusiths, sorry but I don't understand your question. What do you call "default case"?
> 
> If you're using the `StackViewController` provided in the examples, you can of course reduced the width of the overlay container.

default case means when u not change any constraints in your 
library

**Comment by gaetanzanella** [comment]
You can either reduce the scroll view width inside the overlay or directly reduce the overlay view container width.

For example, in the `SearchViewController` : 
```
tableView.pinToSuperview(
    insets: UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10),
    edges: [.left, .right, .bottom]
)
```

**Comment by kunusiths** [comment]
can you tell how to  reduce scroll view please, because reducing table view map view will not be visible please help.

**Comment by gaetanzanella** [comment]
Can you see me your result so far ?

**Comment by kunusiths** [comment]
> Can you see me your result so far ?

so far when i changed table view insets table view is moving but side by it is not transparent scroll view is still there.

**Comment by gaetanzanella** [comment]
Did you try to change the background color of your view controller's view to `.clear` ?

**Comment by kunusiths** [comment]
it worked.Thanx

**Comment by gaetanzanella** [comment]
Yes, copy/paste all the files of the `Sources` folder

**Comment by kunusiths** [comment]
Hi Sir,
  is it possible to push another viewcontroller in sliding view on tapping of table view cell in that slide view.please answer

**Comment by gaetanzanella** [comment]
Hi Sandeep,

For now, unfortunately, you can’t. I’m working on it but I didn't have the time to finish it. 

You'd have to create your own container with its own animation like this :


class MyContainerViewController: UIViewController {
    func push(_ viewController: UIViewController) {
        // add the view controller as a child and put it on top of the other with an animation
    }

    func popViewController() {
        // remove the most top child view controllers with an animation */
    }
}

let myContainer = MyContainerViewController()
let overlayContainer = OverlayContainerViewController()
overlayContainer.viewControllers = [myContainer]

let myOverlay = MyOveralyViewController()
myContainer.push(myOverlay)
overlayContainer.drivingScrollView = myOverlay.tableView

// In the collection delegate or table view delegate or whatever

func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    let newOverlay = MyNewOverlayViewController()
    myContainer.push(newOverlay)
}

Don’t forget to set the drivingScrollView each time a view controller appears !

Let me know if it is what you are looking for,
Gaétan

**Comment by gaetanzanella** [comment]
Hi Sandeep,

For now, unfortunately, you can’t. I’m working on it but I didn't have the time to finish it. 

You'd have to create your own container with its own animation like this :

```
class MyContainerViewController: UIViewController {
    func push(_ viewController: UIViewController) {
        // add the view controller as a child and put it on top of the other with an animation
    }

    func popViewController() {
        // remove the most top child view controllers with an animation */
    }
}

let myContainer = MyContainerViewController()
let overlayContainer = OverlayContainerViewController()
overlayContainer.viewControllers = [myContainer]

let myOverlay = MyOveralyViewController()
myContainer.push(myOverlay)
overlayContainer.drivingScrollView = myOverlay.tableView

// In the collection delegate or table view delegate or whatever

func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    let newOverlay = MyNewOverlayViewController()
    myContainer.push(newOverlay)
}
```

Don’t forget to set the drivingScrollView each time a view controller appears !

**Comment by kunusiths** [comment]
Hello sir,
child.didMove(toParentViewController: self) and child.didMove(toParent: self) are these both the same?. i am getting error and in child.didMove(toParent: self) so i renamed it to child.didMove(toParentViewController: self) .but i am getting other issue when i added this in my app.
i am not able to drag back ground map view but scroll view is scrolling.please help.

**Comment by kunusiths** [comment]
> let myContainer = MyContainerViewController()
> let overlayContainer = OverlayContainerViewController()
> overlayContainer.viewControllers = [myContainer]
> 
> let myOverlay = MyOveralyViewController()
> myContainer.push(myOverlay)
> overlayContainer.drivingScrollView = myOverlay.tableView

this part of code.

let myContainer = MyContainerViewController()
let overlayContainer = OverlayContainerViewController()
overlayContainer.viewControllers = [myContainer]

let myOverlay = MyOveralyViewController()
myContainer.push(myOverlay)
overlayContainer.drivingScrollView = myOverlay.tableView
in which segment it should be added

**Comment by kunusiths** [comment]
please help me
